### ISSUE TITLE
Does it check automatically?

### ISSUE THREAD

**Issue by TheNomad11** [YunoHost-Apps/phpservermon_ynh#7]
Thanks for packaging this app. I am testing it right now. What I wonder. Does it check the servers automatically or do we need to set up cron manually? I am asking because I set up in Cofig (web interface) auto-refresh every 60 seconds, but according to the status page it does not check as "last online" increases minute by minute. Now it says "last online 5 min ago" because it was 5 min ago I last clicked on "Update". It does not do it automatically it seems?

**Comment by BenoitCier** [comment]
I'm not sure...I don't configure any cron, I'm testing

**Comment by TheNomad11** [comment]
Ah, I thought this app is working, as it says Level 7 working and maintained. 

Based on here https://docs.phpservermonitor.org/en/latest/install.html#setting-up-a-cronjob how would this look like on Yunohost?

**Comment by TheNomad11** [comment]
This works. Add to /etc/crontab to check the servers every five minutes:

`*/5 * * * * root /usr/bin/php /var/www/phpservermon/cron/status.cron.php`

**Comment by BenoitCier** [comment]
Thanks, I will upgrade the app for this, yunohost have helpers to add cron job.

**Comment by BenoitCier** [comment]
I upgrade testing branch, you can test it

**Comment by TheNomad11** [comment]
I installed the testing version and set in config - auto-refresh 60 sec but it does not refresh automatically. Does it work for you? 

The other standard version with manual cron works perfectly, I even received my first downtime altert, cool!

**Comment by BenoitCier** [comment]
I have an error in the cron file (missing new line before OEF), the testing branch normally work.
